Override memory limits
HubSpot/Blazar pull request #341
Opened 2017-03-02 19:57 UTC by jonathanwgoodwin

Cc: @gchomatas

2017-03-13 00:30 UTC, gchomatas requested changes

2017-03-13 00:30 UTC, gchomatas commented on BlazarBase/src/main/java/com/hubspot/blazar/base/BuildConfig.java
> +    public List<BuildStep> getSteps() {
It is not a good practice to have getters in the builder. This will allow you to pass around the builder instead of the real object which essentially means that you created a fully mutable object disguised as a builder.

2017-03-13 00:30 UTC, gchomatas commented on BlazarBase/src/main/java/com/hubspot/blazar/base/StepActivationCriteria.java
>  public class StepActivationCriteria implements Predicate<GitInfo> {
This is quite a misleading name. What about ContainsBranchCriterion?

2017-03-13 00:30 UTC, gchomatas commented on BlazarBase/src/main/java/com/hubspot/blazar/external/models/singularity/Resources.java
> +public class Resources {
DockerContainerResources or if you want to be more generic BuildProcessContainerResources

2017-03-13 00:30 UTC, gchomatas commented on BlazarBase/src/main/java/com/hubspot/blazar/external/models/singularity/Resources.java
> +  public static com.hubspot.mesos.Resources toMesosResources(Resources resources) {
Why is this a static methods? If you already have a BuildProcessContainerResources instance you can just do: buildProcessContainerResources.toMesosResoures.toMesosResources();

2017-03-13 00:30 UTC, gchomatas commented on BlazarBase/src/main/java/com/hubspot/blazar/external/models/singularity/Resources.java
> +  public static Resources add(Resources a, Resources b) {
Same here you don't need static: resource.add(anotherResource)
Also implement the add in the class instead of using the mesos class facility and converting back to your class. It is not a good practice to use the implementation of a class  you don't control and it is not meant to be a lib class with a well defined interface. The implementation can change at any time and your add method will change behavior without you having a way to know.

2017-03-13 00:30 UTC, gchomatas commented on BlazarData/src/main/java/com/hubspot/blazar/data/dao/ModuleBuildDao.java
> +  @SqlUpdate("INSERT INTO module_builds (repoBuildId, moduleId, buildNumber, state, buildConfig, resolvedConfig) VALUES (:repoBuildId, :moduleId, :buildNumber, :state, :buildConfig, :resolvedConfig)"
Better name them to buildConfig, resolvedBuildConfig

2017-03-13 00:30 UTC, gchomatas commented on BlazarData/src/main/java/com/hubspot/blazar/data/service/ModuleBuildService.java
> +  public void enqueue(RepositoryBuild repositoryBuild, Module module, BuildConfig baseConfig, BuildConfig resolvedConfig) {
enqueue(RepositoryBuild repositoryBuild, Module module, BuildConfig buildConfig, BuildConfig resolvedBuildConfig)

2017-03-13 00:30 UTC, gchomatas commented on BlazarData/src/main/java/com/hubspot/blazar/data/service/ModuleBuildService.java
> +    ModuleBuild build =
Either change the static method (`queuedBuild`) to use the new args or set all required args in a single builder, i.e. explicitly set the State.QUEUED in the builder.

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/main/java/com/hubspot/blazar/config/ExecutorConfiguration.java
> +    return new ExecutorConfiguration(null, null, null);
ExecutorConfiguration(Optional.absent(), Optional.absent(), Optional.absent());

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/main/java/com/hubspot/blazar/listener/LaunchingRepositoryBuildVisitor.java
> +    BuildConfig baseConfig = buildConfigUtils.getConfigAtRefOrDefault(branch, configPath, sha);
I don't see any try/catch in the `visitLaunching` method. What will happen if this method throws and error?

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/main/java/com/hubspot/blazar/util/BuildConfigUtils.java
> +  public BuildConfig ensureDefaultConfigurationForBuild(BuildConfig buildConfig) {
I think `addMissingBuildConfigSettings` could be more easy to understand than `ensureDefaultConfigurationForBuild`

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/main/java/com/hubspot/blazar/util/BuildConfigUtils.java
> +  public BuildConfig mergeConfig(BuildConfig primary, BuildConfig secondary) {
Add some comments to explain how merge is implemented and why this unconventional mix of substitution of some settings and merge of some others has been chosen.

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/test/java/com/hubspot/blazar/util/BlazarConfigUtilsTest.java
> +  private final GitHubHelper gitHubHelper = mock(GitHubHelper.class);
All these mocked instances could be static

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/test/java/com/hubspot/blazar/util/BlazarConfigUtilsTest.java
> +    BuildConfigUtils configUtils = new BuildConfigUtils(blazarConfiguration, gitHubHelper);
Refactor it to a static and reuse it in all tests

2017-03-13 00:30 UTC, gchomatas commented on BlazarService/src/test/java/com/hubspot/blazar/util/BlazarConfigUtilsTest.java
> +@RunWith(JukitoRunner.class)
You manually mock and you don't inject anything so you don't need JukitoRunner

2017-03-14 16:30 UTC, jonathanwgoodwin commented on BlazarService/src/main/java/com/hubspot/blazar/listener/LaunchingRepositoryBuildVisitor.java
> +    BuildConfig baseConfig = buildConfigUtils.getConfigAtRefOrDefault(branch, configPath, sha);
They will be retried by the stateful event bus so long as the exception is not a `NonRetryableBuildException`.
https://github.com/HubSpot/Blazar/blob/override-memory-limits/BlazarService/src/main/java/com/hubspot/blazar/listener/BuildEventDispatcher.java#L55

2017-03-23 01:03 UTC, gchomatas approved these changes

2017-03-23 01:04 UTC, gchomatas commented
🚢

2017-03-24 14:44 UTC, merged